language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm run test
after_success:
  - npm run coverage
env: 
  global:
    - CODECLIMATE_REPO_TOKEN=c8f435267cefdba7a1fcb2c1177162d26d57b866e9d9fd594e6af0d98d5997e8